### ISSUE TITLE
WS2019 Support?

### ISSUE THREAD

**Issue by limulidae** [MicrosoftDocs/xamarin-docs.zh-tw#15]
Is Windows Server 2019 supported?
I cannot run it.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [硬體加速以提升模擬器效能 (Hyper-V 與 HAXM) - Xamarin](https://docs.microsoft.com/zh-tw/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin&pivots=windows)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-TW/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by CeciAc** [comment]
Hello, @limulidae 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
