### ISSUE TITLE
Translation issue (翻譯問題)

### ISSUE THREAD

**Issue by Tennyleaz** [MicrosoftDocs/xamarin-docs.zh-tw#2]
[翻譯問題]
此文件的中文(台灣)版，第一節的第一行講道
 `在傳統的應用程式開發通常沒有靜態的 main 方法` 
對照原文，應該要是
 `在傳統的應用程式開發通常有靜態的 main 方法` 

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 9c19e82a-ae6c-28cd-291a-f7cafeb1a89a
* Version Independent ID: 8dcea81a-897f-c248-c588-10873a32faeb
* Content: [活動開發週期 - Xamarin](https://docs.microsoft.com/zh-tw/xamarin/android/app-fundamentals/activity-lifecycle/#feedback)
* Content Source: [docs/android/app-fundamentals/activity-lifecycle/index.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-TW/blob/live/docs/android/app-fundamentals/activity-lifecycle/index.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by LisandroSu** [comment]
您好 @Tennyleaz ， 

謝謝您的寶貴意見。 

我們目前正在檢閱您的留言，將會盡快與您連絡。 

順頌時祺 
Microsoft DOCS 國際小組

**Comment by LisandroSu** [comment]
您好，@Tennyleaz ，
 
謝謝您的寶貴意見。
 
我們的編審小組審閱了您提出的語言建議，並接受了這些建議。我們已實作您的意見反應並發佈至   Docs 網站上已更新文章的以下頁面 [活動開發週期 - Xamarin](https://docs.microsoft.com/zh-tw/xamarin/android/app-fundamentals/activity-lifecycle/#feedback)。
 
我們由衷感謝您對文章的貢獻，並期望您繼續提供寶貴的意見。
 
順頌時祺
Microsoft DOCS 國際小組
