### ISSUE TITLE
what is "sDownloadHomepage" ?

### ISSUE THREAD

**Issue by wang-chi** [MicrosoftDocs/xamarin-docs.zh-tw#22]
程式碼await上的是 sDownloadHomepage直接在指派值給變數上的方法 ( intResult ) 不同於前一個範例是使用中繼Task&lt;int&gt;變數來參考工作。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 3e6b1679-7d43-32c2-0ea9-72c2bda2da06
* Version Independent ID: 63828f35-0a1e-1613-bc7f-4f8d95ac3fe7
* Content: [非同步支援概觀 - Xamarin](https://docs.microsoft.com/zh-tw/xamarin/cross-platform/platform/async#feedback)
* Content Source: [docs/cross-platform/platform/async.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-TW/blob/live/docs/cross-platform/platform/async.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by CeciAc** [comment]
您好，@wang-chi
非常感謝您的貢獻。您的意見反應與原始文件相關。 
因此，我們會將此問題移轉至英文存放庫。請由此處查看問題狀態 - https://github.com/MicrosoftDocs/xamarin-docs/issues/1843
我們由衷感謝您對文章的貢獻。  
順頌時祺 
Microsoft DOCS 國際小組
