### ISSUE TITLE
Sample code not found

### ISSUE THREAD

**Issue by wang-chi** [MicrosoftDocs/xamarin-docs.zh-tw#25]
On this doc, the sample code cannot found on Github.
Click Download Sample Code (on first line)-&gt;Browse Code -&gt;Github (this page not found) 

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 6e9eecf7-0edb-5b24-964c-a1ae2e7556ba
* Version Independent ID: 8f9243b4-0f7c-6aac-39e2-913173ea472a
* Content: [DependencyService 簡介 - Xamarin](https://docs.microsoft.com/zh-tw/xamarin/xamarin-forms/app-fundamentals/dependency-service/introduction)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-TW/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/introduction.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @wang-chi 

I've fixed this for the English source. Once the fix is merged, it'll propagate around all the locales.

**Comment by wang-chi** [comment]
Thank you for your help

**Comment by davidbritch** [comment]
In the meantime, the sample you require can be found at https://github.com/xamarin/xamarin-forms-samples/tree/master/DependencyService

**Comment by lichasu** [comment]
Thanks for the help, @davidbritch !

Also, thanks @wang-chi for pointing the issue out!

I'll be closing the Issue now.
