### ISSUE TITLE
錯字

### ISSUE THREAD

**Issue by mfshiu** [MicrosoftDocs/xamarin-docs.zh-tw#27]
錯誤：編輯版面配置檔activity_mail.axml，以下列取代現有的 XML:
正確：activity_main.axml

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 4bc28ea1-445a-7229-ab8d-6d6159fe9bfd
* Version Independent ID: 97b9c884-ff5c-e78f-415c-decfb270ea53
* Content: [Xamarin.Android Fragment 逐步解說-第 1 部分 - Xamarin](https://docs.microsoft.com/zh-tw/xamarin/android/platform/fragments/implementing-with-fragments/walkthrough?tabs=windows#feedback)
* Content Source: [docs/android/platform/fragments/implementing-with-fragments/walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-TW/blob/live/docs/android/platform/fragments/implementing-with-fragments/walkthrough.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by srvbpigh** [comment]
Hello, @mfshiu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by conceptdev** [comment]
This has been fixed in English content, change will appear in localized version soon. Thank you!

**Comment by CeciAc** [comment]
你好，@mfshiu
感谢你的反馈和建议。 

 该文件当前正在进行翻译。我们即将发布这篇文章。

非常感谢你的支持。 

顺祝商祺！

Microsoft DOCS 全球化体验团队
